name: CI

# Controls when the workflow will run
on:
  create:

  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Submodules
        run: git submodule update --init --recursive

      - name: Build
        run: ./ci-build.cmd

      - name: Generate definitions
        run: ./generate-all.cmd

      - name: Copy definitions
        run: ./copy-definitions.cmd

      - name: Upload x64 Release
        uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: artifacts\win-x64\

      - name: Upload x86 Release
        uses: actions/upload-artifact@v2
        with:
          name: win-x86
          path: artifacts\win-x86\

      - name: Upload Definitions
        uses: actions/upload-artifact@v2
        with:
          name: definitions
          path: artifacts\definitions\

  Linux:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Submodules
        run: git submodule update --init --recursive

      - name: Build
        run: ./ci-build.sh

      - name: Upload Linux Release
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: build/Release/linux-x64/

  MacOS:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get Submodules
        run: git submodule update --init --recursive

      - name: Build
        run: ./ci-build.sh

      - name: Upload MacOS Release
        uses: actions/upload-artifact@v2
        with:
          name: osx-x64
          path: build/Release/osx-x64/