name: CI

on:
  create:

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: ./ci-build.cmd

      - name: Generate definitions
        run: ./generate-all.cmd

      - name: Copy definitions
        run: ./copy-definitions.cmd

      - name: Upload x64 Release
        uses: actions/upload-artifact@v2
        with:
          name: win-x64
          path: artifacts\win-x64\

      - name: Upload x86 Release
        uses: actions/upload-artifact@v2
        with:
          name: win-x86
          path: artifacts\win-x86\

      - name: Upload Definitions
        uses: actions/upload-artifact@v2
        with:
          name: definitions
          path: artifacts\definitions\

  Linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive

      - run: echo $PWD

      - name: Build
        run: ./ci-build.sh

      - name: Upload Linux Release
        uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: build/Release/linux-x64/

  MacOS:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
          submodules: recursive

      - name: Build
        run: ./ci-build.sh

      - name: Upload MacOS Release
        uses: actions/upload-artifact@v2
        with:
          name: osx-x64
          path: build/Release/osx-x64/